/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.23
 * Generated at: 2018-06-20 13:54:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/apache-tomcat-8.5.23/webapps/ToolingStandard/WEB-INF/lib/struts2-core-2.3.24.jar!/META-INF/struts-tags.tld", Long.valueOf(1430627084000L));
    _jspx_dependants.put("/WEB-INF/lib/struts2-core-2.3.24.jar", Long.valueOf(1529502805226L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t\r\n");
      out.write("\t<title>首页</title>\r\n");
      out.write("\t\r\n");
      out.write("\t<script src=\"jquery-3.3.1/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t<link rel=\"shortcut icon\" href=\"logoicon.ico\"/>\r\n");
      out.write("\t<link rel=\"bookmark\" href=\"logoicon.ico\"/>\r\n");
      out.write("\t\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/Ys.css\">\r\n");
      out.write("\r\n");
      out.write("<script>\"undefined\"==typeof CODE_LIVE&&(!function(e){var t={nonSecure:\"21040\",secure:\"21051\"},c={nonSecure:\"http://\",secure:\"https://\"},r={nonSecure:\"127.0.0.1\",secure:\"gapdebug.local.genuitec.com\"},n=\"https:\"===window.location.protocol?\"secure\":\"nonSecure\";script=e.createElement(\"script\"),script.type=\"text/javascript\",script.async=!0,script.src=c[n]+r[n]+\":\"+t[n]+\"/codelive-assets/bundle.js\",e.getElementsByTagName(\"head\")[0].appendChild(script)}(document),CODE_LIVE=!0);</script></head>\r\n");
      out.write("\r\n");
      out.write("<body data-genuitec-lp-enabled=\"false\" data-genuitec-file-id=\"wc1-14\" data-genuitec-path=\"/ToolingStandard/WebRoot/index.jsp\">\r\n");
      out.write("\t<!-- header start-->\r\n");
      out.write("\t");
      out.write('\r');
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Head.jsp", out, false);
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write('\r');
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Nav.jsp", out, false);
      out.write("\r\n");
      out.write("\t<div class=\"banner\" data-genuitec-lp-enabled=\"false\" data-genuitec-file-id=\"wc1-14\" data-genuitec-path=\"/ToolingStandard/WebRoot/index.jsp\">\r\n");
      out.write("\t\t<ul class=\"circle\">\r\n");
      out.write("\t\t\t<li class=\"current\"></li>\r\n");
      out.write("\t\t\t<li></li>\r\n");
      out.write("\t\t\t<li></li>\r\n");
      out.write("\t\t\t<li></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- banner start-->\r\n");
      out.write("\t<h2>经营范围</h2>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"banner-a\">\r\n");
      out.write("\t\t<dl>\r\n");
      out.write("\t\t\t<dt>工装衣</dt>\r\n");
      out.write("\t\t\t<dd>\r\n");
      out.write("\t\t\t\t<a href=\"#\">为每一个人打造一套工装标准</a>\r\n");
      out.write("\t\t\t</dd>\r\n");
      out.write("\t\t\t<dd>\r\n");
      out.write("\t\t\t\t<a href=\"#\">我们致力于打造每一条最好的工装裤</a>\r\n");
      out.write("\t\t\t</dd>\r\n");
      out.write("\t\t\t<dd>\r\n");
      out.write("\t\t\t\t<a href=\"#\">邮箱：1057148049@qq.com</a>\r\n");
      out.write("\t\t\t</dd>\r\n");
      out.write("\t\t\t<img src=\"img/q.png\">\r\n");
      out.write("\t\t</dl>\r\n");
      out.write("\t\t<dl>\r\n");
      out.write("\t\t\t<dt>工装裤</dt>\r\n");
      out.write("\t\t\t<dd>\r\n");
      out.write("\t\t\t\t<a href=\"#\">·致我们即将逝去的青春</a>\r\n");
      out.write("\t\t\t</dd>\r\n");
      out.write("\t\t\t<dd>\r\n");
      out.write("\t\t\t\t<a href=\"#\">·穿上工装裤的那一刻 所有规则统统走开</a>\r\n");
      out.write("\t\t\t</dd>\r\n");
      out.write("\t\t\t<dd>\r\n");
      out.write("\t\t\t\t<a href=\"#\">·每个男人都应该拥有一条工装裤</a>\r\n");
      out.write("\t\t\t</dd>\r\n");
      out.write("\t\t\t<img src=\"img/w.png\">\r\n");
      out.write("\t\t</dl>\r\n");
      out.write("\t\t<dl>\r\n");
      out.write("\t\t\t<dt>工装鞋</dt>\r\n");
      out.write("\t\t\t<dd>\r\n");
      out.write("\t\t\t\t<a href=\"#\">·致我们即将逝去的青春</a>\r\n");
      out.write("\t\t\t</dd>\r\n");
      out.write("\t\t\t<dd>\r\n");
      out.write("\t\t\t\t<a href=\"#\">·穿上工装裤的那一刻 所有规则统统走开</a>\r\n");
      out.write("\t\t\t</dd>\r\n");
      out.write("\t\t\t<dd>\r\n");
      out.write("\t\t\t\t<a href=\"#\">·每个男人都应该拥有一条工装裤</a>\r\n");
      out.write("\t\t\t</dd>\r\n");
      out.write("\t\t\t<img src=\"img/y.png\">\r\n");
      out.write("\t\t</dl>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"banner-b\">\r\n");
      out.write("\t\t<ul class=\"circle\">\r\n");
      out.write("\t\t\t<li class=\"current\"></li>\r\n");
      out.write("\t\t\t<li></li>\r\n");
      out.write("\t\t\t<li></li>\r\n");
      out.write("\t\t\t<li></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=banner-c>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"banner-c-1\">\r\n");
      out.write("\t\t\t<div class=\"banner-c-2\">\r\n");
      out.write("\t\t\t\t<img src=\"img/yuwenle.jpg\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"p1\">\r\n");
      out.write("\t\t\t\t<p>Common\r\n");
      out.write("\t\t\t\t\tSense（简称CMSS），相信对于关注街头潮流的你，不会不熟悉这个名字的新定义。对的，现在是余文乐的个人品牌。 概念 CMSS\r\n");
      out.write("\t\t\t\t\tCMSS(5张) Common\r\n");
      out.write("\t\t\t\t\tSense（简称CMSS）的品牌概念一直很模糊，或者说是有点故弄玄虚的暧昧感的宣传方式。虽然Common\r\n");
      out.write("\t\t\t\t\tSense（简称CMSS）的消息出来有一段时间了，但是很多具体的细节都没有浮面。大家靠的只能是猜测。只知道从EAST\r\n");
      out.write("\t\t\t\t\tTOUCH的余文乐个人专栏Common Sense开始，不断介绍一些个人的爱好为主。\r\n");
      out.write("\t\t\t\t\t甚至是一个完整的品牌那样按系列推出，还是以单品推出为主的形式也不太清楚。当然CatWhy更愿意看到是后者那种形式。\r\n");
      out.write("\t\t\t\t\t风格虽然Common\r\n");
      out.write("\t\t\t\t\tSense（简称CMSS）只是发布了几款产品的谍照而已，不过可以看出这些产品的设计风格还是很符合余文乐个人的喜好的。基本都已很basic的款式为主，然后在其细节上花功夫。\r\n");
      out.write("\t\t\t\t\t其实目前看来，Common Sense（简称C\r\n");
      out.write("\t\t\t\t\tMSS）确实更似用来直接传达余文乐的个人审美。从初步曝光的产品中看到，只算是加上了Common\r\n");
      out.write("\t\t\t\t\tSense或CMSS的logo为主，没有太大的设计可言。与其入手余文乐的“Common Sense”，不如制作属于自己的“Common\r\n");
      out.write("\t\t\t\t\tSense”更好，这样来得更有共鸣感。\r\n");
      out.write("\t\t\t\t\t你可以到布料市场或者网上寻找能够表达自己sense的绣章或者一些简单的加工设计，缝到自己的喜欢的素体服饰上就好。我始终认为，衣服除了好看以外，更多是寻找自己的共鸣感。这也是笔者OneTwo很喜欢街头潮流的原因，大家都在坚持实现自己的理念。</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"banner-d-1\">\r\n");
      out.write("\t\t\t<div class=\"banner-d-2\">\r\n");
      out.write("\t\t\t\t<img src=\"img/cgx.jpg\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"p2\">\r\n");
      out.write("\t\t\t\t<p>CLOT是香港著名艺人陈冠希创办的凝结集团（CLOT\r\n");
      out.write("\t\t\t\t\tFAMILY）的简称及该公司旗下潮流服装品牌名称。凝结集团是一个LIFESTYLE的公司，由香港著名艺人陈冠希创办于2003年6月。主要以创作服装（包括CLOT品牌服装以及在香港的JUICE店铺）、策划PARTY、帮助服装公司做Consultant等。CLOT品牌服装是中国第一潮牌，在全球潮流品牌中占有一席之地。Edison陈冠希2003年创办了自己的服装品牌CLOT，并自己参与服装的设计、用料等各个方面，成为中国第一潮牌，并在世界上都有一定的影响力。CLOT是一个LIFESTYLE的公司，创作服装，包括CLOT品牌服装以及在香港的JUICE店铺、策划PARTY、帮助香港一些公司做consultant，例如NIKE、PEPSI…、更包括CLOT自己的音乐，现成员包括：陈冠希、MC仁、、DJTommy、厨房仔、恭硕良、赵晨浩、BOSS（环球热力兄弟）等一起，CLOT是一个FAMILY，是一个不可分开的家庭。而他的店铺JUICE也成为香港游客的一旅游胜地CLOT也经常会与一些其他大品牌生产合作产品，像LEⅥ'S，NIKE，PEPSI等品牌。前段时间Edison在上海长乐路开了自己第二家CLOT店ACU（由于租期问题，现已由李晨的NPC代替）\r\n");
      out.write("\t\t\t\t\t第一家在香港 ACU开店当天的情况 可谓盛况空前 各大明星潮人都出现在ACU藤原浩等等。与Nike的合作，鞋款的Nick\r\n");
      out.write("\t\t\t\t\tname为“kiss of death（死亡之吻）”，Nike Air Max 1 NL X Clot\r\n");
      out.write("\t\t\t\t\t全球限量1299/对，想买也买不到.鞋身用卡其和橙色混搭，后跟有CLOT的标志和中国图腾，鞋头的透明设计也是鞋子的一大亮点！</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- footer start  -->\r\n");
      out.write("\t<div class=\"footer\">\r\n");
      out.write("\t\t<div class=\"footer-t\">\r\n");
      out.write("\t\t\t<div class=\"footer-inner\">\r\n");
      out.write("\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t<dt>设计理念</dt>\r\n");
      out.write("\t\t\t\t\t<dd>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\">为每一个人打造一套工装标准</a>\r\n");
      out.write("\t\t\t\t\t</dd>\r\n");
      out.write("\t\t\t\t\t<dd>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\">我们致力于打造每一条最好的工装裤</a>\r\n");
      out.write("\t\t\t\t\t</dd>\r\n");
      out.write("\t\t\t\t\t<dd>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\">邮箱：1057148049@qq.com</a>\r\n");
      out.write("\t\t\t\t\t</dd>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t<dt>潮流时尚</dt>\r\n");
      out.write("\t\t\t\t\t<dd>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\">·致我们即将逝去的青春</a>\r\n");
      out.write("\t\t\t\t\t</dd>\r\n");
      out.write("\t\t\t\t\t<dd>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\">·穿上工装裤的那一刻 所有规则统统走开</a>\r\n");
      out.write("\t\t\t\t\t</dd>\r\n");
      out.write("\t\t\t\t\t<dd>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\">·每个男人都应该拥有一条工装裤</a>\r\n");
      out.write("\t\t\t\t\t</dd>\r\n");
      out.write("\t\t\t\t</dl>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"code\">\r\n");
      out.write("\t\t\t\t\t<img src=\"img/code_05.jpg\" />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"footer-b\">\r\n");
      out.write("\t\t\t<p>版权所有 2016 - 2017 黄晓杰</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
